FROM openjdk-11.0.9.1_1-slim

# copy the pom and src code to the container
COPY target/demo-0.0.1-SNAPSHOT.jar /demo.jar

# package our application code
# RUN mvn clean package

# the second stage of our build will use open jdk 11 on alpine 3.9
#FROM openjdk:11.0.7-jdk-slim

# copy only the artifacts we need from the first stage and discard the rest
#COPY --from=MAVEN_BUILD /target/demodocker-0.0.1-SNAPSHOT.jar /demo.jar

# set the startup command to execute the jar
CMD ["java", "-jar", "/demo.jar"]
